version: "3"
services:
  build-aio:
    build:
      context: .
      dockerfile: tools/dockerbuild/build.dockerfile
    image: angular-ja/build-aio
    volumes: 
      - ./aio-ja:/aio-ja
      - ./scripts:/scripts
      - ./build-out:/origin/aio/dist
  watch-aio:
    build:
      context: .
      dockerfile: tools/dockerbuild/watch.dockerfile
    image: angular-ja/watch-aio
    ports:
      - "4200:4200"
    volumes: 
      - ./aio-ja:/aio-ja
      - ./scripts:/scripts
    environment:
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING:-false}
